[package]
name = "control_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
arrayvec = { version = "0.7.2", features = ["serde"] }
num-traits = "0.2.15"
petgraph = "0.6.3"
rbl_circular_buffer = "0.1.2"
serde = { version = "1.0.164", features = ["derive"] }
serde_yaml = "0.9.21"
