[package]
name = "control-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
petgraph = "0.6.4"
control-system-derive = { path = "control-system-derive" }


[workspace]
members = [
    "control-system-derive",
    "control-system-blocks",
]